### ISSUE TITLE
Cannot write empty layer to DB

### ISSUE THREAD

**Issue by enocholumide** [enocholumide/GMCM3_Software_Eng#27]
For empty layer with no feature, the table is not written to the DB.

Please see gif below:

![iissuedbdev](https://user-images.githubusercontent.com/24214602/33999715-824047ea-e0eb-11e7-9491-db518b732c8d.gif)

**Comment by iboates** [comment]
If i recall correctly, I think is is no longer an issue because we cannot create layers from inside the DB catalog anymore.
