### ISSUE TITLE
Not enough information from getTables()

### ISSUE THREAD

**Issue by enocholumide** [enocholumide/GMCM3_Software_Eng#29]
Can the getTables() also give the table geometry type?

I know I can get it from readTable() method, but that means I will be doing the db operation 10x  if I need to know the geom type of 10 tables.

**Comment by enocholumide** [comment]
Is this solved yet @isaac?

**Comment by iboates** [comment]
Yes, with the last merge: https://github.com/enocholumide/GMCM3_Software_Eng/pull/36

readTable now returns an ArrayList of String[2]. first entry is table name and second is type
