### ISSUE TITLE
Application window spans multiple screens and first-time popup is on both

### ISSUE THREAD

**Issue by iboates** [enocholumide/GMCM3_Software_Eng#37]
If you have multiple monitors, the application will span across both of them, but keep all the contents on the main screen.

The first-time database config popup also appears directly in the middle of the "display", so it is right in the middle where the screens split

**Comment by enocholumide** [comment]
Please give screen shot of what is going on

**Comment by iboates** [comment]
![img_20171216_163524](https://user-images.githubusercontent.com/13814358/34071966-42a4cd32-e27f-11e7-9306-2f3098b492cd.jpg)

![img_20171216_163235](https://user-images.githubusercontent.com/13814358/34071940-f3572b76-e27e-11e7-8e35-ee2f553a58cf.jpg)

Can't do a screenshot because the problem is seen when you have a multi-monitor setup.

First image is the application spanning two screens, second is the database setup window appearing split by the two monitors
